site_name: NTR resultat
site_url: https://ybkamaleri.github.io
site_description: Resultattjenester for NTR
site_author: Yusman K

repo_url: https://github.com/ybkamaleri/traume/
edit_uri: ""

nav:
  - Hjem: index.md
  - Om: about.md
theme: readthedocs
extra_javascript:
  - js/gitlink.js
