---
params:
  rapportTitle: !r Rapport title
  rapportDato: !r Sys.Date()
title: "`r params$rapportTitle`"
date: "`r params$rapportDato`"
output:
  word_document:
    highlight: "kate"
---

# Traume og Alarm

Antall traume og alarm

```{r setup, include=FALSE, warning=TRUE, message=TRUE}

#############
## Knitr opt
#############
knitr::opts_chunk$set(
  ## fig.path = paste0('figures/ntr-', Hospital), #mappe for figurer
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  include = TRUE)

## ======
## DATA
## ======
ns <- session$ns
hospValg <- input$hosp_valg
## datoFra <- input$dato_rapport[1]
## datoTil <- input$dato_rapport[2]

datoFra <- "2005-01-01"
datoTil <- "2018-01-01"

dataDT <- akutt2[!duplicated(ntrid) &
                    Hospital == (hospValg) &
                      dateSykehus >= as.POSIXct(datoFra, format = "%Y-%m-%d") &
                       dateSykehus <= as.POSIXct(datoTil, format = "%Y-%m-%d"), ]

antallNTR <- dim(dataDT)[1]



## Skadeskjema
skadeDT <- skade[!duplicated(ntrid) &
                    !is.na(ntrid) &
                   Hospital == (hospValg) &
                    dateSykehus >= as.POSIXct(datoFra, format = "%Y-%m-%d") &
                       dateSykehus <= as.POSIXct(datoTil, format = "%Y-%m-%d"),]


## Ulykkeskjema
ulykkeDT <- ulykke[!duplicated(ntrid) &
                    !is.na(ntrid) &
                   Hospital == (hospValg) &
                    dateSykehus >= as.POSIXct(datoFra, format = "%Y-%m-%d") &
                       dateSykehus <= as.POSIXct(datoTil, format = "%Y-%m-%d"),]


## prehospitalskjema
prehospDT <- prehosp[!duplicated(ntrid) &
                    !is.na(ntrid) &
                   Hospital == (hospValg) &
                    dateSykehus >= as.POSIXct(datoFra, format = "%Y-%m-%d") &
                       dateSykehus <= as.POSIXct(datoTil, format = "%Y-%m-%d"),]


```

## Kjønn

Antall traume og kjønn

```{r gender, message=TRUE}
dataTab <- dataDT[!is.na(gender), .N, by = gender]
dataTab[, gender := as.character(gender)]
dataTab[.(gender = c("1", "2"), to = c("Menn", "Kvinner")), on = "gender", gender := i.to]
data.table::setnames(dataTab, "gender", " ")
kable(dataTab)
```
