#+Title: Analyser for NTR
#+Date: 1 mai 2018

* Kategorisering
- Sykehus
- Region
* Liggerdøgn
- Hvordan regner man liggerdøgn?
- Startdato
- Sluttdato
* Skadekoder
- Ullyketype
  + Ullyketype med transport ulykke. Bør velge bare når svaret i /acc_transport/ er
    JA når man analysere type transport ulykke)
- Skadekoder
* Tilhørighet
- Hvilket sykehus for forskjellige skjemaer eg. Skadegradering og ulykke når skal
  analysere skade pga. sykkelulykke (annet skjema fra annet sykehus) og
  Skadegradering fra annet sykehus. eg. "NTR-000285"
* Førarbeid [0/3]
Ting må gjøres for analsyen
- [ ] Liste over Reshid mot HF og RHF er oppdatert og samsvær med databasen
- [ ] Koder doublesjekke med kodebok. Ingen ekstra koder i datautrekk som ikke er i kodebook (definisjonskatalogen)
- [ ] Tid er registret

* AIS [2/8]
- [X] Kode 91000.1 vises som 010000.1 i GUI. Check at datadump har 091000.1 (Ingen som har 09**)
- [X] kode ~******.9~ betyr skadegrad er ukjent
- [ ] AIS ~******.1~ skal bort i analysen for nevne. Lage bare en knapp hvis man vil
  inkluderer skadegrad 1
- [ ] Bare høyest skadegradering som teller
- [ ] ISS > 15 betyr alvorlig skade. For ISS beregning er kvadrat av 3 alvorligste AIS
- [ ] Beregn eg. vanligste skade ved en vist type ulykke
- [ ] Lage AIS fane uten ulykketype eller skade mekanismen
- [ ] Beholder duplikater
* Analyse ønsker [1/11]
De er basert på diskusjonen med NTR og bestillingsdokument
- [ ] Dashboard med ISS > 15
- [X] Død etter 30 dager (som det er nå)
- [ ] Filter for dato Nasjonal - inj_start_date (Traume skjema)
- [ ] Filter for dato Sykehus - ed_arrival_dtg (Akutt skjema)
  + Antall fordelt på tid og ukedag
- [ ] Ulykke og pre-hospital skjema fra sykehus 1 (hosp_serial_num fra Traume Skjema)
- [ ] Filter for Alder
- [ ] Filter for kjønn
- [ ] Filter for penetrerende skade
- [ ] Sykehus opphold for liggertid (Intensiv skjema) hvis mulig
- [ ] Transport forskjellige koder
- [ ] Forklarer alle analysene i shiny
