#+Title: Bugfix log for NTR
#+Date: 22 mai 2018

#+options: toc:nil

* Flowchart for analysen
* Features [6/10]
 - [X] Sortere tabellen alphabetisk
 - [X] Align checkboxGroupInput (k)
   - bruk CSS og filen ligger under *www* mappe.
 - [X] Tab for 'Generelle info' (k)
   - bruk CSS for å kunne endre farge. Nå er det valg for farge 'yellow' som er endret
 - [X] Antall traume valueBox (k)
   - base funksjon med unique er raskere enn data.table sine funksjoner dvs.
     + length(!duplicated(ntrid))
     + uniqueN(ntrid)
   - CSS for bakgrunnfarge og tekst i custom.css fil. Viktig å inkludere ~!important~
     for det skal funker
 - [ ] Liggerdøgn
 - [ ] Reset knapp
 - [X] Antall alder og kjønn
 - [X] Antall for hver ulykke typer og transport typer
 - [ ] Tid fra AMK ble oppringt til fremmet til hendelsesstedet
 - [ ] Knapp for å inkludere AIS 1 dvs. mild skade

* Bugfix
** AIS kode for hud ikke vises
Koden ble konvertert til numeric. Derfor forsvinner første tallet i koden som er
~0~. Beholder koden som character evt. bruker ~as.character~ for sikrehet skyld.

* Kommentar/observasjoner
Tilbakemelding til IKT og kommentarer til data uttrekk som kan forbedres eller endres:
1. Variablenavn ~Valgte ais-koder~ fra /skade/ datasett bør har variablenavn med bare *et ord*.
