sidebar <-  dashboardSidebar(width = 250,
                             sidebarMenu(id = "sidebarMain",
                                         menuItem("Generell informasjon",
                                                  tabName = "tab_dashboard",
                                                  icon = icon("info-circle")),
                                         menuItem("Valg data",
                                                  ## tabName = "tab_valg_data",
                                                  icon = icon("database"), startExpanded = TRUE,
                                                  menuItem("Analysenivå:",
                                                           ## tabName = "tab_analyse_level",
                                                           ## icon = icon("sliders"),
                                                           selectInput(inputId = "analyse_level_in",
                                                                       label = "Valg nivå",
                                                                       choices = c("Hele landet" = 1,
                                                                                   "RHF" = 2,
                                                                                   "HF" = 3,
                                                                                   "Sykehus" = 4),
                                                                       selected = 1),
                                                           conditionalPanel(condition = "input.analyse_level_in != 1",
                                                                            uiOutput("health_level_out"))),
                                                  menuItem("Tidsrom:",
                                                           ## tabName = "tab_periode",
                                                           ## icon = icon("calendar"),
                                                           dateRangeInput(inputId = "tidsrom_in",
                                                                          label = "Valg dato fra og til",
                                                                          start = Sys.Date() - 360, #alt. min date
                                                                          end = Sys.Date(),
                                                                          separator = "til",
                                                                          format = "dd-mm-yyyy",
                                                                          startview = "month",
                                                                          language = "no",
                                                                          weekstart = 1)),
                                                  ## tags$br(), #blank line
                                                  ## fluidRow(
                                                  ##   ## Filter button
                                                  ##   column(4, offset = 2,
                                                  ##          actionButton(inputId = "input_filter",
                                                  ##                       label = "Kjør filter",
                                                  ##                       icon = icon("arrow-right"))
                                                  ##          )),
                                                  menuItem("Vis rapport",
                                                           tabName = "tab_rapport",
                                                           icon = icon("share"))
                                                  ),
                                         menuItem("Andre filtreringer:", icon = icon("cogs"),
                                                  menuItem("Kjønn",
                                                           tabName = "tab_kjonn",
                                                           icon = icon("venus-mars"),
                                                           selectInput(inputId = "kjonn_in",
                                                                       label = "Valg kjønn",
                                                                       choices = c("Alle" = 1,
                                                                                   "Kvinner" = 2,
                                                                                   "Menn" = 3),
                                                                       selected = 1)),
                                                  menuItem("Alder",
                                                           tabName = "tab_alder",
                                                           icon = icon("user"),
                                                           sliderInput(inputId = "alder_in",
                                                                       label = "Valg aldersgruppe",
                                                                       min = 0, max = 120,
                                                                       value = c(0,100)))),
                                         tags$hr(), #linje
                                         menuItem("Ulykke",
                                                  tabName = "tab_ulykke",
                                                  icon = icon("bar-chart")),
                                         menuItem("Akutt",
                                                  tabName = "tab_ulykke",
                                                  icon = icon("bar-chart")),
                                         menuItem("Intensiv",
                                                  tabName = "tab_ulykke",
                                                  icon = icon("bar-chart")),
                                         menuItem("Skadegradering",
                                                  tabName = "tab_ulykke",
                                                  icon = icon("bar-chart")),
                                         tags$hr(), #linje
                                         menuItem("Virksomhetsdata",
                                                  tabName = "virk_hospt",
                                                  icon = icon("h-square"),
                                                  menuItem("Sykehusnavn:",
                                                           tabName = "virk_sykehus",
                                                           uiOutput("virk_sykehus_out")
                                                           ),
                                                  menuItem("Valg tidsrom:",
                                                           tabName = "virk_periode",
                                                           dateRangeInput(inputId = "virk_date_in",
                                                                          label = "Valg dato fra og til",
                                                                          ## start = Sys.Date() - 30, #alt. min date
                                                                          end = Sys.Date(),
                                                                          separator = "til",
                                                                          format = "dd-mm-yyyy",
                                                                          startview = "month",
                                                                          language = "no",
                                                                          weekstart = 1)),
                                                  menuItem("Vis rapport", tabName = "tab_virk_rap",
                                                           icon = icon("share")))

                                         )
                             )
