app <- ShinyDriver$new("../")
app$snapshotInit("mytest2")

app$snapshot()
app$setInputs(sidebarItemExpanded = character(0))
app$snapshot()
app$setInputs(analyse_level_in = "2")
app$setInputs(health_level_in = "Helse Sør-Øst")
app$snapshot()
app$setInputs(analyse_level_in = "3")
app$snapshot()
app$snapshot(list(output = "health_level_out"))
app$setInputs(health_level_in = "Helse Bergen")
app$snapshot()
