app <- ShinyDriver$new("../")
app$snapshotInit("test01")

app$snapshot()
app$setInputs(sidebarItemExpanded = character(0))
app$setInputs(input_analyse_level = "2")
app$setInputs(input_health_level = "Helse-Midt Norge")
app$setInputs(input_analyse_level = "3")
app$setInputs(input_health_level = "Helse Bergen")
app$setInputs(input_analyse_level = "4")
app$setInputs(input_health_level = "Mo i Rana")
app$setInputs(sidebarItemExpanded = "Valgdata")
app$setInputs(sidebarItemExpanded = "Kjønn")
app$setInputs(input_kjonn = "2")
app$setInputs(sidebarItemExpanded = "Alder")
app$setInputs(input_alder = c(0, 62))
app$setInputs(input_alder = c(22, 62))
